config/routes.rb
Tweetbuffer::Application.routes.draw do
  #API Url
  #api session
  match "api/check_sign_in_session" => "api/sessions#check_sign_in_session"
  #api tweet
  match "api/twitter_account_list" => "api/twitter_users#twitter_account_list"

  match "api/post_to_twitter" => "api/twitter_users#post_to_twitter"
  match "api/send_to_buff" => "api/twitter_users#send_to_buff"
  match 'twitter_users/delete_buffer/:id' => 'twitter_users#delete_buffer', :as => :delete_buffer, :via => :get
  match 'twitter_users/edit_buffer/:id' => 'twitter_users#edit_buffer', :as => :edit_buffer, :via => :get
  match "twitter_users/:id/update_buffer" => "twitter_users#update_buffer", :as => :update_buffer
  match "/settings/account/new" => "twitter_users#add_an_account", :as => :add_an_account
  match "invite_team_member" => 'TwitterUsers#invite_team_member', :via => :post, :as => :invite_team_member

  post "/save_settings" => "twitter_users#save_settings", :as => :save_settings

  resources :timezones

  resources :tweet_histories

  resources :tweet_intervals

  resources :timeframes
  
  resources :suggestions
  
  match "contact" => "contact#index", :as=> "contact"



  get "/goodies" => "goodies#index", :as => :goodies
  get "suggestions/tweet_suggestion/:twitter_name" => "suggestions#tweet_suggestion"
  
  match "setting_suggestion" => "Suggestions#setting_suggestion", :as => :setting_suggestion, :via => :get
  match "get_category/:id" => "Suggestions#get_category", :as => :get_category, :via => :post
  
  get "/update_setting_time" => "TwitterUsers#update_setting_time"

  resources :subcriptions
  resources :payment_notifications

  match "paypall_callback" => "dashboard#paypall_callback", :as => :paypall_callback

  resources :plans
  get "/plans/:id/signup" => "plans#get_plan_clicked_when_signup", :as => :get_plan_clicked_when_signup_plan
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  devise_for :users, :controllers => {:registrations => "devise/registration", :sessions => "devise/session", :passwords => "devise/password"}
 
  root :to => 'Home#index'  

  get "/settings/account" => "dashboard#account", :as => :account_settings
  put "/settings/account/update" => "dashboard#update", :as => :account_password_update
  
  match "/twitter/account/:twitter_name" => "twitterUsers#index", :as => :twitter_user
  match "/twitter/" => "twitterUsers#index", :as => :twitter_user2
  scope "dashboard" do
    get "/facebook/:twitter_name" => "TwitterUsers#index", :as => :facebook_user
    get "/twitter/:twitter_name" => "TwitterUsers#index", :as => :twitter_user
    
    controller :dashboard do
      get   "" => :show, :as => :dashboard
      get   "settings/twitter" => :twitter, :as => :twitter_settings
    end
  end
  
  get "/settings/twitter/:twitter_name" => "TwitterUsers#settings", :as => :twitter_settings
  get "/settings/facebook/:twitter_name" => "TwitterUsers#settings", :as => :facebook_settings
  
  scope "facebook" do
    controller :facebook_sessions do
      get   "authorize" => :new, :as => :facebook_authorize_account
      get   "callback" => :oauth_callback, :as => :facebook_callback
    end
    #    get "/settings" => "TwitterUsers#settings", :as => :facebook_settings
  end
   
  match "twitter/bitly_apis/delete/:id" => "bitly_apis#delete_bitly", :as => :delete_bitly, :via => :get
  
  scope "twitter" do
    #    match "add_account" => "dashboard#add_account", :as => :add_account
    get "/new" => "dashboard#add_account", :as => :add_account
    
    resources :bitly_apis do
      collection do
        post "save_detail" => :create_or_update
      end
    end
    
    controller :twitter_sessions do
      get   "authorize" => :new, :as => :twitter_authorize_account
      get   "callback" => :oauth_callback, :as => :twitter_callback
    end
    
    get "/" => "TwitterUsers#index", :as => :twitter_users
    
    get "/queue/:twitter_name" => "TwitterUsers#queue", :as => :twitter_user_queue
    get "/performance/:twitter_name" => "TwitterUsers#performance", :as => :twitter_user_performance
    
    get "/tweet_to_twitter" => "TwitterUsers#tweet_to_twitter", :as => :tweet_to_twitter
    get "/tweet_from_buffer/:id" => "TwitterUsers#tweet_from_buffer", :as => :tweet_from_buffer
    
    get "/twitter_account_list" => "TwitterUsers#twitter_account_list"
    
    #    get "/settings" => "TwitterUsers#settings", :as => :twitter_settings
    
    get "/settings/other_time_interval" => "TwitterUsers#other_time_interval", :as => :other_ti
    get "/settings/default_interval" => "TwitterUsers#default_interval", :as => :default_ti
    post "/settings/update_timezone" => "TwitterUsers#update_timezone", :as => :update_timezone
    post "/settings/update_notify" => "TwitterUsers#update_notify", :as => :update_notify

    scope ":twitter_name" do
      controller :buffer_preferences do
        get     "buffers"     => :index,    :as => :twitter_user_buffer_preferences
        post    "buffers"     => :create,   :as => :twitter_user_buffer_preferences
        get     "buffers/new" => :new,      :as => :new_twitter_user_buffer_preference
      end
      
      controller :suggestions do
        post    "suggestions"     => :create,   :as => :twitter_user_suggestions
      end

      scope ":buffer_name" do
        resources :tweets do
          collection do
            post :sort
          end
        end

        controller :buffer_preferences do
          get     "edit"  => :edit,             :as => :edit_twitter_user_buffer_preference
          get     "/"     => :show,             :as => :twitter_user_buffer_preference
          put     "/"     => :update,           :as => :twitter_user_buffer_preference
          delete  "/"     => :destroy,          :as => :twitter_user_buffer_preference
          get     "time"  => :new_tweet_time,   :as => :new_twitter_user_buffer_preference_tweet_time
        end

        post    "time" => "TimeDefinitions#create_time",  :as => :twitter_user_buffer_preference_tweet_time
        delete  "time" => "TimeDefinitions#destroy_time", :as => :twitter_user_buffer_preference_tweet_time
      end
    end
  end

end

app/controllers/buffer_preferences_controller.rb
class BufferPreferencesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :twitter_account_required
  before_filter :get_twitter_user

  respond_to :html, :json

  def index
    @buffer_preferences = @twitter_user.buffer_preferences.all(:conditions => ["deleted_at IS NULL"])
    respond_with(@twitter_user, @buffer_preferences)
  end

  def show
    @buffer_preference = @twitter_user.buffer_preferences.find_by_permalink(params[:buffer_name])
    respond_with(@twitter_user, @buffer_preference) do |format|
      format.json {
        render(:json => { :twitter_user => {
              :login => @twitter_user.login,
              :name => @twitter_user.name},
            :buffer_preference => {
              :tweet_mode => @buffer_preference.tweet_mode,
              :name => @buffer_preference.name,
              :permalink => @buffer_preference.permalink}})
      }
    end
  end

  def new
    @buffer_preference = @twitter_user.buffer_preferences.new()
    respond_with(@twitter_user, @buffer_preference)
  end
  
  def create
   
    if request.xhr?
      @error = false

      # messages will hold an array of {:twitter_name =>  , :error=> false/true, :error_type => }
      @messages = []
      
      @max_tweets = max_tweet_buffer_for_user(current_user)
      @allaccounts = params[:twitter_accounts][:name].split(',')
      @twitter_user = current_user.twitter_users.find_by_permalink(params[:twitter_name])
      
      @allaccounts.map!{|account| current_user.twitter_users.find_by_permalink(account)}
      @allaccounts.unshift(@twitter_user)
      
      if params[:buffer_preference][:name].blank?
        @error = true
        @messages.push({:twitter_name=> '', :error=> true, :error_type=>'empty_name_error'})
      else
        first = true;
        @allaccounts.each{ |tw_account|
          error = false
          
          @buffers = BufferPreference.where("twitter_user_id = ? AND status = ?", tw_account.id, "uninitialized").count
          
          if @twitter_user.time_setting.blank?
            error = true
            @messages.push({:twitter_name=> tw_account.login, :error=> true, :error_type=>'time_settings_blank_error'})
          else
            if (@buffers.eql?(@max_tweets))
              error = true
              @messages.push({:twitter_name=> tw_account.login, :error=> true, :error_type=>'max_tweets_error'})
            end 
          end
          
          @error = error if first
          
          if !error
            
            buffer_preference = tw_account.buffer_preferences.create(params[:buffer_preference].merge(:status => "uninitialized"))
            buffer_preference = buffer_preference.update_run_at_new.last
            ordered_buffers = BufferPreference.where("status = ? AND twitter_user_id =?", "uninitialized", tw_account.id).order("run_at ASC")
            active_time = ordered_buffers.first.run_at.to_date rescue Date.today
            buffers = tw_account.buffer_preferences.oldest_order
            if buffers.nil? 
              count_buffer = 0
            else
              count_buffer = buffers.count 
            end 
            @messages.push({:twitter_name=> tw_account.login, :error=> false, :error_type=>''})
            
            if first
              @buffer_preference = buffer_preference
              @ordered_buffers = ordered_buffers
              @active_time = active_time  
            end
          end 
          first = false;
        };
      end
    end
  end

  def edit
    @buffer_preference = @twitter_user.buffer_preferences.find_by_permalink(params[:buffer_name])
    respond_with(@twitter_user, @buffer_preference)
  end

  def update
    @buffer_preference = @twitter_user.buffer_preferences.find_by_permalink(params[:buffer_name])
    @buffer_preference.update_attributes(params[:buffer_preferences])
    respond_with(@twitter_user, @buffer_preference) do |format|
      format.json { render(:json => {:status => :ok})}
    end
  end

  def destroy
    respond_with(@twitter_user, @buffer_preference)
  end

  def new_tweet_time
    @buffer_preference = @twitter_user.buffer_preferences.find_by_permalink(params[:buffer_name])
    render :layout => false
  end

  protected

  def get_twitter_user
    @twitter_user = current_user.twitter_users.find_by_permalink(params[:twitter_name])
    if @twitter_user.account_type.eql?("twitter")
      redirect_to(twitter_settings_path) and return if @twitter_user.blank?
    else
      redirect_to(facebook_settings_path) and return if @twitter_user.blank?
    end
  end

  def update_run_at
    twitter_user = TwitterUser.find_by_permalink(params[:twitter_name])
    time_setting = TimeSetting.find_by_twitter_user_id(twitter_user.id)
    
    buffers = BufferPreference.where("twitter_user_id = ? AND status = ?", twitter_user.id, "uninitialized")
    b = buffers.last
    b.run_at = nil
    b.save!
    
    times = time_setting.time_period.split(",")
    
    buffer = buffers[buffers.count - 2]
    last_time = (buffer.run_at).strftime("%H:%M")
    last_date = (buffer.run_at).strftime("%Y-%m-%d")
    i = times.index(last_time)
    
    if times[i+1].nil?
      run_at = times.first
      @buffer_preference.update_attributes({:run_at => run_at})
    else
      run_at = times[i+1]
      
      year = last_date.split("-")[0]
      month = last_date.split("-")[1]
      day = last_date.split("-")[2]
      hour = run_at.split(":")[0]
      min = run_at.split(":")[1]
      
      time = Time.utc(year, month, day, hour, min, nil, "+00:00")
      @buffer_preference.update_attributes({:run_at => time})
    end
  end
    
  def max_tweet_buffer_for_user(user)
    accounts = TwitterUser.find_all_by_user_id(user.id).count
    subcription = Subcription.active_subcription(user).first
    subcription.plan.num_of_tweet_in_buffer
  end

end

app/helpers/buffer_preference_helper.rb
module BufferPreferenceHelper

  def tweet_mode_selected(comp, mode)
    mode.to_s.include?(comp.to_s) ? "ui-selected" : ""
  end

end

app/views/buffer_preferences/_buffer_basic.html.haml
- time_definition = buffer_preference.time_definitions.first(:conditions => {:day_of_week => day})
= simple_form_for(time_definition, :url => twitter_user_buffer_preference_tweet_time_path(@twitter_user, buffer_preference)) do |form|
  .span-15.last
    .span-15.last
      SEND ON DAY WHATEVER GOES HERE
  .span-15.last.clearfix
    .span-3
      Starting at
    .span-7
      .time-select.inline{:"data-altfield" => "#start_at"}
      = form.input :start_at, :as => :hidden
    .span-5.last
      X tweets per day
  .span-15.last
    = form.input :interval, :as => :hidden, :html_input => {:value => true}
    = form.input :interval_length, :collection => TimeDefinition::INTERVALS
  .span-15.last
    .span-5.right
      =form.button :submit

app/views/buffer_preferences/_buffer_count.html.haml
= @count_buffer

app/views/buffer_preferences/_buffer_daily.html.haml
#daily.tabs-container
  %ul.tabs
    - Date::DAYNAMES.each do |day|
      %li
        %a{:href => "#daily_#{day.downcase}"}
          = day
  - Date::DAYNAMES.each do |day|
    .clearfix{:id => "daily_#{day.downcase}"}
      - day_idx = Date::DAYNAMES.index(day)
      - if expert
        = render(:partial => "/buffer_preferences/buffer_expert", :locals => {:buffer_preference => buffer_preference, :day => day_idx})
      - else
        = render(:partial => "/buffer_preferences/buffer_basic", :locals => {:buffer_preference => buffer_preference, :day => day_idx})

app/views/buffer_preferences/_buffer_expert.html.haml
- times = buffer_preference.time_definitions.all(:conditions => {:day_of_week => day})
.span-15.last
  .span-15.last
    SEND ON DAY WHATEVER GOES HERE
.span-15.last
  .span-3
    Send at:
  .span-7
    %ul.time-list{:class => buffer_preference.tweet_mode}
      - times.each do |time|
        %li.time
          = "#{time.start_hour}:#{time.start_minute}"
          %a.delete-time
            = t("buffer_preferences.edit.links.delete_time")
      - if times.count == 0
        %li.no-times
          = t("buffer_preferences.edit.warnings.no_times")
  .span-5.last
    X tweets per day
.span-15.last
  %a.dialog{:href => new_twitter_user_buffer_preference_tweet_time_path}
    =t("buffer_preferences.edit.links.add_new_time")

app/views/buffer_preferences/_buffer_warning.haml
%h2 Warning
%p.buffer-warning
  You have selected to use
  %span.buffer-new-type NEW TYPE
  instead of
  %span.buffer-old-type
    #{buffer_preference.tweet_mode.to_s.titleize}
%p.buffer-warning
  This will clear all of your previous settings for this buffer. If you wish to continue, please click "accept" below.
.buffer-warning-linkset
  %a.buffer-accept{:href => "#accept"}
    = t("buffer_preferences.warning.accept")
  %a.buffer-cancel{:href => "#cancel"}
    = t("buffer_preferences.warning.cancel")

app/views/buffer_preferences/_form.html.haml
= form.input :name
= form.button :submit

app/views/buffer_preferences/create.js.erb
<% if !@error %>
      $('#buffer_wrapper').html("<%= escape_javascript render(:partial => "/twitter_users/queue", :locals => {:buffer => @buffer_preference, :ordered_buffers => @ordered_buffers, :active_time => @active_time}) %>");
	  $('#buffer_count_text_blue_set').html("<%= escape_javascript render(:partial => "buffer_count", :locals => {:count_buffer => @count_buffer}) %>");
      $('#loader-buffer').hide();
      $('#tweet_text').val('');
      
<% end %>
$('#loader-buffer').hide();

<% @messages.each{|message|%>
	<% if (message[:twitter_name] == @twitter_user.login) and !message[:error]%>
		successqueue_notification("<%= message[:twitter_name]%>");
	<%else%>
		<% if message[:error] %>
			<% if message[:twitter_name].empty? and message[:error_type]=='empty_name_error'%>
				emptytweet_error("<%= message[:twitter_name]%>") ;
			<% else %>
				<% if message[:error_type] == 'time_settings_blank_error' %>
					timesettings_error("<%= message[:twitter_name]%>");
				<% end %>
				<% if message[:error_type] == 'max_tweets_error' %>
					maxtweets_error("<%= message[:twitter_name]%>");
				<% end %>
			
			<% end %>
		<% end %>
	<% end %>	
<% } %>

app/views/buffer_preferences/edit.html.haml
.span-24.last#buffer-basis
  .container#buffer-selector.append-bottom
    %ul#buffer-basis-select.selectable
      %li{:"data-type" => "weekly", :class => tweet_mode_selected(:weekly, @buffer_preference.tweet_mode)}
        = t("buffer_preferences.edit.weekly")
      %li{:"data-type" => "daily", :class => tweet_mode_selected(:daily, @buffer_preference.tweet_mode)}
        = t("buffer_preferences.edit.daily")
    %ul#buffer-expertise-select.selectable
      %li{:"data-type" => "basic", :class => tweet_mode_selected(:basic, @buffer_preference.tweet_mode)}
        = t("buffer_preferences.edit.basic")
      %li{:"data-type" => "expert", :class => tweet_mode_selected(:expert, @buffer_preference.tweet_mode)}
        = t("buffer_preferences.edit.expert")
  .container#buffer-editor.append-bottom
    #loading-screen.hidden
      Loading...
    #weekly_basic.mode-container
      - if @buffer_preference.tweet_mode == :weekly_basic
        = render(:partial => "/buffer_preferences/buffer_basic", :locals => {:buffer_preference => @buffer_preference, :day => 0})
    #weekly_expert.mode-container
      - if @buffer_preference.tweet_mode == :weekly_expert
        = render(:partial => "/buffer_preferences/buffer_expert", :locals => {:buffer_preference => @buffer_preference, :day => 0})
    #daily_basic.mode-container
      - if @buffer_preference.tweet_mode == :daily_basic
        = render(:partial => "/buffer_preferences/buffer_daily", :locals => {:buffer_preference => @buffer_preference, :expert => false})
    #daily_expert.mode-container
      - if @buffer_preference.tweet_mode == :daily_expert
        = render(:partial => "/buffer_preferences/buffer_daily", :locals => {:buffer_preference => @buffer_preference, :expert => true})
    #buffer-change-warning.hidden
      =render(:partial => "/buffer_preferences/buffer_warning", :locals => {:buffer_preference => @buffer_preference})

app/views/buffer_preferences/index.html.haml
.span-24.last
  %h2= t("buffer_preferences.index.header")
  %p!= t("buffer_preferences.index.description", :user => current_user.email)
  .tabs-container.buffer-tabs#buffer
    %ul.tabs
      - @buffer_preferences.each do |buffer_preference|
        %li
          %a{:href => "##{buffer_preference.permalink}"}
            #{buffer_preference.name}
      %li
        %a{:href => "#new_buffer"}
          =t("buffer_preferences.index.tabs.new_buffer")
    - @buffer_preferences.each do |buffer_preference|
      .clearfix.buffer-panel{:id => buffer_preference.permalink}
        .buffer-preference-pane-links.clearfix
          %ul.link-nav.right
            %li
              %a.dialog.new-tweet{:href => new_tweet_path(@twitter_user, buffer_preference), :"data-width" => 450}
                = t("buffer_preferences.links.new_tweet")
            %li
              %a{:href => edit_twitter_user_buffer_preference_path(@twitter_user, buffer_preference)}
                = t("buffer_preferences.links.edit_buffer")
        %hr
        .buffer-preference-pane-table
          = render(:partial => "/tweets/table", :locals => {:tweets => buffer_preference.tweets})
    #new_buffer.clearfix
      .span-4.twitter-photo
        cool image here
      .span-18.buffer-list.last
        %h3=t("buffer_preferences.index.new_buffer_header")
        %hr
        = simple_form_for([@twitter_user, @twitter_user.buffer_preferences.new], :remote => true) do |form|
          = render(:partial => "/buffer_preferences/form", :locals => {:form => form})

app/views/buffer_preferences/new.html.haml
.span-24
  %h2=t("buffer_preferences.new.header")
  %p!= t("buffer_preferences.new.description", :user => @twitter_user.login)

  = simple_form_for([@twitter_user, @buffer_preference]) do |form|
    = render(:partial => "/buffer_preferences/form", :locals => {:form => form})

app/views/buffer_preferences/new_tweet_time.html.haml
%form{:action => twitter_user_buffer_preference_tweet_time_path, :method => :post, :id => "new_tweet_time_form"}
  .time-select.inline{:"data-altfield" => "#time_definition_start_at"}
  %input{:type => :hidden, :name => "time_definition[start_at]", :id => "time_definition_start_at", :value => "11:00"}
  %input{:type => :hidden, :name => "authenticity_token", :value => form_authenticity_token}
  %input{:type => :hidden, :name => "time_definition[day_of_week]", :id => "time_definition_day_of_week", :value => "0"}
  %input{:type => :hidden, :name => "time_definition[buffer_preference_id]", :id => "time_definition_buffer_preference_id", :value => @buffer_preference.id}
  %noscript
    %input{:type => :submit, :value => "Save"}

= javascript_include_tag("jquery_ujs")
:javascript
  $(document).ready(function(){
    $("div.time-select.inline").each(function(i,el){
      $(el).timepicker({
         altField: $(el).data("altfield") || null,
         defaultTime: "11:00"
      });
    });
    if($.buffereditor.currentMode == "daily_expert"){
      $("input#time_definition_day_of_week").val($.buffereditor.currentDay);
    }
  })

  $("#dialog").dialog('option', "buttons", {
    "Create" : function(){
      var $this = $(this);
      var form = $("form#new_tweet_time_form");
      $.post(form.attr("action"), form.serializeArray(), function(data){
        $.buffereditor.addTime(data);
        $this.dialog("close");
      }, "json");
    },
    "Cancel" : function(){
      $(this).dialog("close");
    }
  });