config/routes.rb
Tweetbuffer::Application.routes.draw do
  #API Url
  #api session
  match "api/check_sign_in_session" => "api/sessions#check_sign_in_session"
  #api tweet
  match "api/twitter_account_list" => "api/twitter_users#twitter_account_list"

  match "api/post_to_twitter" => "api/twitter_users#post_to_twitter"
  match "api/send_to_buff" => "api/twitter_users#send_to_buff"
  match 'twitter_users/delete_buffer/:id' => 'twitter_users#delete_buffer', :as => :delete_buffer, :via => :get
  match 'twitter_users/edit_buffer/:id' => 'twitter_users#edit_buffer', :as => :edit_buffer, :via => :get
  match "twitter_users/:id/update_buffer" => "twitter_users#update_buffer", :as => :update_buffer
  match "/settings/account/new" => "twitter_users#add_an_account", :as => :add_an_account
  match "invite_team_member" => 'TwitterUsers#invite_team_member', :via => :post, :as => :invite_team_member

  post "/save_settings" => "twitter_users#save_settings", :as => :save_settings

  resources :timezones

  resources :tweet_histories

  resources :tweet_intervals

  resources :timeframes
  
  resources :suggestions
  
  match "contact" => "contact#index", :as=> "contact"



  get "/goodies" => "goodies#index", :as => :goodies
  get "suggestions/tweet_suggestion/:twitter_name" => "suggestions#tweet_suggestion"
  
  match "setting_suggestion" => "Suggestions#setting_suggestion", :as => :setting_suggestion, :via => :get
  match "get_category/:id" => "Suggestions#get_category", :as => :get_category, :via => :post
  
  get "/update_setting_time" => "TwitterUsers#update_setting_time"

  resources :subcriptions
  resources :payment_notifications

  match "paypall_callback" => "dashboard#paypall_callback", :as => :paypall_callback

  resources :plans
  get "/plans/:id/signup" => "plans#get_plan_clicked_when_signup", :as => :get_plan_clicked_when_signup_plan
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  devise_for :users, :controllers => {:registrations => "devise/registration", :sessions => "devise/session", :passwords => "devise/password"}
 
  root :to => 'Home#index'  

  get "/settings/account" => "dashboard#account", :as => :account_settings
  put "/settings/account/update" => "dashboard#update", :as => :account_password_update
  
  match "/twitter/account/:twitter_name" => "twitterUsers#index", :as => :twitter_user
  match "/twitter/" => "twitterUsers#index", :as => :twitter_user2
  scope "dashboard" do
    get "/facebook/:twitter_name" => "TwitterUsers#index", :as => :facebook_user
    get "/twitter/:twitter_name" => "TwitterUsers#index", :as => :twitter_user
    
    controller :dashboard do
      get   "" => :show, :as => :dashboard
      get   "settings/twitter" => :twitter, :as => :twitter_settings
    end
  end
  
  get "/settings/twitter/:twitter_name" => "TwitterUsers#settings", :as => :twitter_settings
  get "/settings/facebook/:twitter_name" => "TwitterUsers#settings", :as => :facebook_settings
  
  scope "facebook" do
    controller :facebook_sessions do
      get   "authorize" => :new, :as => :facebook_authorize_account
      get   "callback" => :oauth_callback, :as => :facebook_callback
    end
    #    get "/settings" => "TwitterUsers#settings", :as => :facebook_settings
  end
   
  match "twitter/bitly_apis/delete/:id" => "bitly_apis#delete_bitly", :as => :delete_bitly, :via => :get
  
  scope "twitter" do
    #    match "add_account" => "dashboard#add_account", :as => :add_account
    get "/new" => "dashboard#add_account", :as => :add_account
    
    resources :bitly_apis do
      collection do
        post "save_detail" => :create_or_update
      end
    end
    
    controller :twitter_sessions do
      get   "authorize" => :new, :as => :twitter_authorize_account
      get   "callback" => :oauth_callback, :as => :twitter_callback
    end
    
    get "/" => "TwitterUsers#index", :as => :twitter_users
    
    get "/queue/:twitter_name" => "TwitterUsers#queue", :as => :twitter_user_queue
    get "/performance/:twitter_name" => "TwitterUsers#performance", :as => :twitter_user_performance
    
    get "/tweet_to_twitter" => "TwitterUsers#tweet_to_twitter", :as => :tweet_to_twitter
    get "/tweet_from_buffer/:id" => "TwitterUsers#tweet_from_buffer", :as => :tweet_from_buffer
    
    get "/twitter_account_list" => "TwitterUsers#twitter_account_list"
    
    #    get "/settings" => "TwitterUsers#settings", :as => :twitter_settings
    
    get "/settings/other_time_interval" => "TwitterUsers#other_time_interval", :as => :other_ti
    get "/settings/default_interval" => "TwitterUsers#default_interval", :as => :default_ti
    post "/settings/update_timezone" => "TwitterUsers#update_timezone", :as => :update_timezone
    post "/settings/update_notify" => "TwitterUsers#update_notify", :as => :update_notify

    scope ":twitter_name" do
      controller :buffer_preferences do
        get     "buffers"     => :index,    :as => :twitter_user_buffer_preferences
        post    "buffers"     => :create,   :as => :twitter_user_buffer_preferences
        get     "buffers/new" => :new,      :as => :new_twitter_user_buffer_preference
      end
      
      controller :suggestions do
        post    "suggestions"     => :create,   :as => :twitter_user_suggestions
      end

      scope ":buffer_name" do
        resources :tweets do
          collection do
            post :sort
          end
        end

        controller :buffer_preferences do
          get     "edit"  => :edit,             :as => :edit_twitter_user_buffer_preference
          get     "/"     => :show,             :as => :twitter_user_buffer_preference
          put     "/"     => :update,           :as => :twitter_user_buffer_preference
          delete  "/"     => :destroy,          :as => :twitter_user_buffer_preference
          get     "time"  => :new_tweet_time,   :as => :new_twitter_user_buffer_preference_tweet_time
        end

        post    "time" => "TimeDefinitions#create_time",  :as => :twitter_user_buffer_preference_tweet_time
        delete  "time" => "TimeDefinitions#destroy_time", :as => :twitter_user_buffer_preference_tweet_time
      end
    end
  end

end

app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base
  include ::TwitterAuth::OauthUser

  # Constants
  TWITTER_ATTRIBUTES = [
    :name,
    :location,
    :description,
    :profile_image_url,
    :url,
    :protected,
    :friends_count,
    :statuses_count,
    :followers_count,
    :favourites_count,
    :time_zone,
    :utc_offset,
  ]

  # Associations
  belongs_to :user
  
  with_options :dependent => :destroy do |tu|
    tu.has_many :buffer_preferences
    tu.has_many :suggestions
  
    tu.has_one :tweet_interval
    tu.has_one :time_setting
  end

  # Attributes
  attr_protected :twitter_id, :remember_token, :remember_token_expires_at

  # Validations
  validates_uniqueness_of :twitter_id, :message => "ID has already been taken."

  # Callbacks
  before_save :update_permalink

  def self.new_from_twitter_hash(hash)
    raise ArgumentError, 'Invalid hash: must include screen_name.' unless hash.key?('screen_name')
    raise ArgumentError, 'Invalid hash: must include id.' unless hash.key?('id')

    user = TwitterUser.new
    user.twitter_id = hash['id'].to_s
    user.login = hash['screen_name']

    TWITTER_ATTRIBUTES.each do |att|
      user.send("#{att}=", hash[att.to_s]) if user.respond_to?("#{att}=")
    end

    user
  end

  def assign_twitter_attributes(hash)
    TWITTER_ATTRIBUTES.each do |att|
      send("#{att}=", hash[att.to_s]) if respond_to?("#{att}=")
    end
  end

  def update_twitter_attributes(hash)
    assign_twitter_attributes(hash)
    save
  end

  def twitter
    ::TwitterAuth::Dispatcher::Oauth.new(self)
  end

  def to_param
    self.login.parameterize
  end

  protected

  def update_permalink
    self.permalink = self.to_param
  end

end

app/controllers/api/twitter_users_controller.rb
class Api::TwitterUsersController < ApplicationController
  protect_from_forgery :except => [:twitter_account_list, :post_to_twitter, :send_to_buff]
  before_filter :authenticate_user!
  
  def twitter_account_list
    @twitter_users = current_user.twitter_users
    
    respond_to do |format|
      format.xml
    end
  end
  
  def post_to_twitter
    unless params[:tweet_message].empty?
      if params[:twitter_name].blank?
        @tweet_status = 0
        @tweet_message = "Failed : You don't have twitter account name."
      else
        user = current_user.twitter_users.find_by_permalink(params[:twitter_name])
        unless user.blank?
          twitter_config(user)
          client = Twitter::Client.new
          status = CGI.unescape(params[:tweet_message])
          url = status.match(/https?:\/\/[\S]+/)
          unless url.nil?
            bitly_api = current_user.bitly_api
            unless bitly_api.nil?
              user = bitly_api.bitly_name
              apikey = bitly_api.api_key
              version = "3"
              bitly_url = "http://api.bit.ly/shorten?version=#{version}&longUrl=#{url}&login=#{user}&apiKey=#{apikey}"
                
              buffer = open(bitly_url, "UserAgent" => "Ruby-ExpandLink").read
              result = JSON.parse(buffer)
              short_url = result['results'][url.to_s]['shortUrl']
              status = status.gsub(url.to_s, short_url)
            end
          end
          begin
            client.update(status)
            @tweet_status = 1
            @tweet_message = "Success : Your tweet has been posted."
          rescue
            @tweet_status = 0
            @tweet_message = "Failed : Status is a duplicate."
          end
        else
          @tweet_status = 0
          @tweet_message = "Failed : Can't find twitter account name with #{params[:twitter_name]}."
        end
      end
    else
      @tweet_status = 0
      @tweet_message = "Failed : Tweet message can't be blank."
    end
    respond_to do |format|
      format.xml
    end
  end
  
  def send_to_buff
    unless params[:tweet_message].empty?
      if params[:twitter_name].blank?
        @tweet_status = 0
        @tweet_message = "Failed : You don't have twitter account name."
      else
        twitter_user = current_user.twitter_users.find_by_permalink(params[:twitter_name])
        if twitter_user.blank?
          @tweet_status = 0
          @tweet_message = "Failed : Can't find twitter account name with #{params[:twitter_name]}."
        else
          if twitter_user.time_setting.blank?
            @tweet_status = 0
            @tweet_message = "Failed : You must setting quee setting first."
          else
            buffer_preference = twitter_user.buffer_preferences.create(:name => CGI.unescape(params[:tweet_message]),:status => "uninitialized")
            error_messages = buffer_preference.errors
            if error_messages.blank?
              @tweet_status = 1
              @tweet_message = "Success : Your tweet has been sent to buff."
              #              update_run_at
            else
              @tweet_status = 0
              @tweet_message = "Failed : Tweet message has already been taken."
            end
          end
        end
      end
    else
      @tweet_status = 0
      @tweet_message = "Failed : Tweet message can't be blank."
    end
    respond_to do |format|
      format.xml
    end
  end
  
  protected
  
  def update_run_at
    @ti = @twitter_user.time_setting
    @tf = @ti.timeframe

    if @tf
      @post_at = @tf.value.to_i
      if @tf.unit.eql?("minutes")
        run_at = Time.now + @post_at.minutes
      elsif @tf.unit.eql?("hours")
        run_at = Time.now + @post_at.hours
      end
    else
      #block to check if user use other_interval
      buffer_not_success = @twitter_user.buffer_preferences.find(:all, :conditions => ["status = ? AND run_at IS NOT NULL","uninitialized"])
      minute_hours = @ti.other_interval.split("|") # => ["10:15 PM","h.m.p"...]
      mh_count = minute_hours.count
      all_run = 0
      mark_index = 0
      year = Time.now.strftime('%Y')
      month = Time.now.strftime('%m')
      day = Time.now.strftime('%d')
      date = Time.now.strftime('%D')
      hour = Time.now.strftime('%H')
      minute = Time.now.strftime('%M')
      run_sat = nil
      # iterate all minute_hours
      unless buffer_not_success.blank?
        minute_hours.each_with_index do |minute_hour, index|
          last_run = buffer_not_success.last.run_at.strftime("%H:%M")
          if minute_hour.eql?(last_run)
            if index < (mh_count - 1)
              tes = (index+1)
            elsif index == (mh_count - 1)
              tes = 0
            end
            run_sat = minute_hours[tes.to_i]
          end
        end
      else
        run_sat = minute_hours[0]
      end
      dj_min_hour = run_sat.split(":") rescue minute_hours[0].split(":")
      last_buffer = buffer_not_success.last
      last_buffer_run = last_buffer.run_at rescue Time.now
      last_buffer_added_time = last_buffer.added_time rescue 0
      if last_buffer_run.strftime("%H:%M").eql?(minute_hours.last) || last_buffer_added_time > 0
        last_run = last_buffer_run.strftime("%H:%M").eql?(minute_hours.last)? last_buffer_added_time+1 : last_buffer_added_time
        run_at = Time.utc(year,month,day,dj_min_hour[0],dj_min_hour[1]) +last_run.day
        added_time = last_buffer_added_time + 1 if run_sat.eql?(minute_hours.first)
      else
        run_at = Time.utc(year,month,day,dj_min_hour[0],dj_min_hour[1])
        added_time = 0
      end
    end
    @run_at = run_at
    @buffer_preference.update_attributes({:run_at => @run_at, :added_time => added_time})
  end
end
  

app/helpers/twitter_users_helper.rb
module TwitterUsersHelper
  
end

app/views/twitter_users/_display_bitly.html.haml
%div{:style => "display: inline-block;"}
  %table
    %tr
      %th{:style=> "text-align: center; width: 150px;"} Username
      %th{:style=> "text-align: center; width: 270px;"} API Key
      %th
      %th
      %th
    %tr
      %td{:style=> "text-align: center;"}= @bitly.bitly_name
      %td{:style=> "text-align: center;"}= @bitly.api_key
      %td{:style=> "width: 40px; text-align: center; font-size: 13px;"}
        = link_to_function 'Edit', "$('.form_bitly').show(); $('.display_bitly').hide();"
      %td{:style=> "width: 40px; text-align: center; font-size: 13px;"}
        = link_to 'Delete', delete_bitly_path(@bitly.user_id), confirm: "Are you sure want to delete your bitly?"

app/views/twitter_users/_edit_buffer.html.haml
#updateTweetContainer
  #loader
    =image_tag("ajaxLoader.gif")
    %br
    Posting your tweet
  #loader-update-buffer
    =image_tag("ajaxLoader.gif")
    %br
    Updating tweet to buffer
  = form_for @buffer, :remote => true, :url => update_buffer_path(@buffer.id) do |f|
    #addTweetTextAreaContainer
      = f.text_area :name, :id => "tweet_text", :placeholder => "add tweet here ...", :class => "transparentInput"
    %div{:style => "clear:both;"}
    #bufferAccionsButtonsContainer
      #bufferUpdateBufferButton
        = submit_tag "", :class => "rockwellRegular bufferUpdateBufferButton", :onclick => "$('#loader-update-buffer').show();"
      #bufferPostNowButton
        %input{:value => "", :type => "button",:class => "rockwellRegular bufferPostNowButton", :onclick => "$.get('#{tweet_to_twitter_path}',{tweet:$('#tweet_text').val(),twitter_name:'#{@twitter_user.login}'}); $('#loader').show();"}
      - if @twitter_user.account_type.eql?("twitter")
        #bufferQueueSettingsButton
          %input{:type => "button",:class => "queue_settings",:class => "rockwellRegular bufferQueueSettingsButton", :onclick => "window.location='#{twitter_settings_path(@twitter_user.login)}'"} 
      - else
        #bufferQueueSettingsButton
          %input{:type => "button",:class => "queue_settings",:class => "rockwellRegular bufferQueueSettingsButton", :onclick => "window.location='#{facebook_settings_path(@twitter_user.login)}'"} 

app/views/twitter_users/_form_buffer.html.haml
#addTweetContainer
  #goProContainer
    = image_tag("goProImage.png")
    %a.rockwellRegular{:href => "#"} View advantage
    #goProCounter
      %span{:id => "counter"}
  = form_for @buffer_preference, :url => "/twitter/#{@twitter_user.login}/buffers", :remote => true do |f|
    #addTweetTextAreaContainer
      = f.text_area :name, :id => "tweet_text", :placeholder => "add tweet here ...", :class => "transparentInput"
    #bufferAccionsButtonsContainer
      = hidden_field :twitter_accounts, :name
      #bufferAddQueueButton
        = submit_tag "", :class => "rockwellRegular bufferAddQueueButton", :onclick => "jQuery('html, body').animate({scrollTop:0}, 'slow'); $('#loader-buffer').show(); refreshSelectedTwitterAccounts();"
      #bufferPostNowButton
        %input{:value => "", :type => "button",:class => "rockwellRegular bufferPostNowButton", :onclick => "$.get('#{tweet_to_twitter_path}',{tweet:$('#tweet_text').val(),twitter_name:'#{@twitter_user.login}'}); $('#loader').show();"}
      #bufferQueueSettingsButton
        %input{:type => "button",:class => "rockwellRegular bufferQueueSettingsButton", :onclick => "window.location='#{twitter_settings_path(@twitter_user.login)}'"}   
      #bufferViewSuggestionsButton
        %input{:type => "button",:class => "sugestions",:class => "rockwellRegular bufferQueueSuggestionsButton", :onclick => "showDialog('Post Suggestions', '/suggestions?twitter_name=#{@twitter_user.login}'); return false;"}   

app/views/twitter_users/_queue.html.haml
#buffer_wrapper
  - ordered_buffers.each_with_index do |buffer, i|
    - puts 'BUFFER:' + buffer.to_json
    - if active_time != buffer.run_at.to_date or i == 0
      #bufferTweetsHeader
        = image_tag("tweetBufferBirdImage.png", :class => "tweetBufferBirdImage")
        %span.rockwellRegular.bufferTweetsListDate
          = show_buffer_date_title(buffer)
        - active_time = buffer.run_at.to_date
        %a{:href => "#"}
          %img.bufferTweetsListArrow{:src => "/assets/bufferDownArrow.png"}/
    #bufferTweetsListContainer
      #bufferTweetsRow
        %p.bufferTweetText.rockwellRegular
          %span.bufferTweetUser> @#{@twitter_user.login} &nbsp;
          = buffer.name
        %p.bufferTweetDate.rockwellRegular
          = "Queued for #{buffer.run_at.strftime('%I:%M %p')}" unless buffer.run_at.nil?
        .bufferTweetActionsButtonsContainer
          .bufferTweetEditActionButton
            = link_to "Tweet", tweet_from_buffer_path(buffer.id), :params => "twitter_name", :class => "bufferTweetActionButtonLink myriadProNormal"
          .bufferTweetArchiveActionButton
            = link_to "Edit", edit_buffer_path(buffer.id), :params => "twitter_name", :class => "bufferTweetActionButtonLink myriadProNormal", :remote=> true
          .bufferTweetArchiveActionButton
            = link_to "Delete", delete_buffer_path(buffer.id), :params => "twitter_name", :class => "bufferTweetActionButtonLink myriadProNormal"

app/views/twitter_users/add_an_account.html.haml
#middle.mainMiddleAddFaceTwitt
  #signInContainer
    #signInTitleContainer
      %p#signInTitle
        Add your Twitter or Facebook account
      %p#signInSubTitle
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    .separator
    #configContainer
      =image_tag "littleBird.png", :id => "addFaceTwittAccountLittleBird"
      #addAccountsTabsContainer
        #add_face_account_tab
          = link_to "Facebook", facebook_authorize_account_path, :class => "rockwellRegular"
        #add_twitt_account_tab
          = link_to "Twitter", twitter_authorize_account_path, :class => "rockwellRegular"
      .separator
      #add_face_twitt_last_p
        %p.rockwellRegular Within a few seconds you'll be topping up your Buffer to enjoy the hassle-free way of sharing consistently.
#sponsors.mainSponsors

app/views/twitter_users/default_interval.html.haml
=form_tag save_settings_path do
  =hidden_field :timeframe, :user_id, :value => @twitter_user.user.id
  =hidden_field :timeframe, :twitter_user_id, :value => @twitter_user.id
  =select_tag "timeframe[timeframe_id]", options_for_select(@options), :onchange => "$('#timeframe_form_container').load('#{other_ti_path}')"
  =submit_tag "Update"

app/views/twitter_users/edit_buffer.html.haml
#post_notice
#general_dialog
-unless @is_updated_interval.nil?
  #interval_not_updated.error
    = "#{@is_updated_interval}. #{link_to("Setup here", twitter_settings_path(:twitter_name => @twitter_user.login)) unless @twitter_user.nil?}".html_safe

-if @twitter_user.nil?
  You need to authorize us to use your Twitter account.
  %a{:href => twitter_authorize_account_path}
    authorize now
-else
  .wrapper
    #go_pro
      %div{:style => "display: inline-block;"}
      =image_tag("/assets/bluebox.jpg", :style => "width: 32px; height: 32px;")
      %div{:style => "display: inline-block; text-align: left;"}
        %span{:style => "color: #F6C312; font-size: 15px; font-weight: bold;"}
          Go
        %span{:style => "color: #3D6CB4; font-size: 15px; font-weight: bold;"}
          Pro!
        %br
        %i
          =link_to "View advantage", plans_path, :class => "adv_link"

    #tweet_stuff
      .user_twitter_detail
        #profile_image
          = profile_image(@twitter_user, "_normal", 64, 64)
        #buffer_count
          %img{:src => "/assets/t_count.jpg"}
        - if user_signed_in?
          - if @plans.plan.name.eql?("Free")
            %span{:style => "color: rgb(49, 133, 195); font-weight: bold; position: absolute; font-size: 32px; margin-top: 6px; margin-left: -57px;"} #{@count_buffer}
          - elsif @plans.plan.name.eql?("Pro")
            %span{:style => "color: rgb(49, 133, 195); font-weight: bold; position: absolute; font-size: 32px; margin-top: 6px; margin-left: -57px;"} #{@count_buffer}
          - elsif @plans.plan.name.eql?("Premium")
            %span{:style => "color: rgb(49, 133, 195); font-weight: bold; position: absolute; font-size: 32px; margin-top: 6px; margin-left: -57px;"} Unlimited tweets per day

        #user_login
          =@twitter_user.login
        #mini_panel
          %ul{:style => "list-style: none;"}
            %li{:style => "font-size: 14px; font-weight: bold;"}
              %a{:href => twitter_authorize_account_path, :style => "color: #3468BB"}
                %img{:src => "/assets/add_blue.png", :width => 24, :height => 24} Add Account
            %li{:style => "font-size: 14px; font-weight: bold;"}
              %a{:href => "#", :style => "color:#3468BB", :onclick => "showDialog('Switch account','#{twitter_account_list_path}'); return false;"}
                %img{:src => "/assets/refresh_24.png", :width => 24, :height => 24} Switch Account
      .tweet_form_buffer
        #loader
          =image_tag("ajaxLoader.gif")
          %br
          Posting your tweet
        #loader-buffer
          =image_tag("ajaxLoader.gif")
          %br
          Adding tweet to buffer
        =form_for @buffer_preference, :url => "/twitter/#{@twitter_user.login}/buffers", :remote => true do |f|
          #addTweetTextAreaContainer
            = f.text_area :name, :id => "tweet_text", :placeholder => "add tweet here ...", :class => "transparentInput"
          #button_container
            =submit_tag "", :class => "add_to_queue", :onclick => "$('#loader-buffer').show();"
            #bufferPostNowButton
              %input{:value => "", :type => "button",:class => "rockwellRegular bufferPostNowButton", :onclick => "$.get('#{tweet_to_twitter_path}',{tweet:$('#tweet_text').val(),twitter_name:'#{@twitter_user.login}'}); $('#loader').show();"}
            #bufferQueueSettingsButton
              %input{:type => "button",:class => "queue_settings",:class => "rockwellRegular bufferQueueSettingsButton", :onclick => :onclick => "window.location='#{twitter_settings_path(:twitter_name => @twitter_user.login)}'"} 
            %input{:type => "button",:class => "post_now", :onclick => "$.get('#{tweet_to_twitter_path}',{tweet:$('#tweet_text').val(),twitter_name:'#{@twitter_user.login}'}); $('#loader').show();"}
            %input{:type => "button",:class => "queue_settings", :onclick => "window.location='#{twitter_settings_path(:twitter_name => @twitter_user.login)}'"}
    #separator
      // buffer list and ads
    #ads
      = image_tag("/assets/advertise.jpg")
    #buffer_list
      %span{:style => "font-size: 15px; font-weight: bold; display: block; text-align: center;"}
        Queue | Performance | Analitics
      %br
      #buffer_wrapper
        - old_buffer = nil
        -@buffers.each do |buffer|
          - if old_buffer != buffer.added_time
            %div{:style => "background: #79C1F3; margin: 5px 0 5px 0;"}
              %span{:style => "float: left; margin-top: -10px;"}
                %img{:src => "/assets/birds_64/5.png", :width => 34, :height => 34}
              = time_in_word(buffer.added_time, buffer.run_at)
          #buffer_name_container{:class =>cycle("even","odd"), :onmouseover => "$('#actions_#{buffer.id}').css('visibility','visible');", :onmouseout => "$('#actions_#{buffer.id}').css('visibility','hidden')"}
            = buffer.name
            %br
            %span{:style => "color: #7BC2EE; font-style: italic; font-size: 13px;"}
              = "Queued for #{buffer.run_at.strftime('%H:%M %p')}" unless buffer.run_at.nil?
            %span{:id => "actions_#{buffer.id}", :style => "float: right; visibility: hidden; margin-top: -15px;"}
              #tweet_now{:onclick => ""}
                = link_to image_tag("/assets/twitter.png"), tweet_from_buffer_path(buffer.id), :params => "twitter_name"
              #edit_buffer{:onclick => ""}
                = link_to image_tag("/assets/edit.png"), :controller => "twitter_users", :action => "edit_buffer", :id => @buffer.id, :twitter_name => current_user.id
              #delete_buffer{:onclick => "$('#loader-delete-buffer').show(); jQuery('html, body').animate({scrollTop:0}, 'slow');"}
                = link_to image_tag("/assets/close-icon.png"), delete_buffer_path(buffer.id), :remote => true
          - old_buffer = buffer.added_time
      
      

app/views/twitter_users/edit_buffer.js.erb
$('#loader-edit-buffer').hide();
$('#addTweetContainer').replaceWith('<%= escape_javascript(render(:partial => "twitter_users/edit_buffer")) %>');

app/views/twitter_users/other_time_interval.html.haml
= form_tag save_settings_path do
  =hour_select("tfname[hour]")
  =minute_select("tfname[minute]")
  =meridian("tfname[meridian]")

%br
%input{:type => "button", :onclick => "$('#timeframe_form_container').load('#{default_ti_path}')"}
    

app/views/twitter_users/twitter_account_list.html.haml
%ul{:style => "list-style: none;"}
  -@twitter_users.each do |twitter_user|
    %li
      %div{:class => cycle("even","odd")}
        =link_to twitter_user.login, twitter_user_path(twitter_user.login)