config/routes.rb
Tweetbuffer::Application.routes.draw do
  #API Url
  #api session
  match "api/check_sign_in_session" => "api/sessions#check_sign_in_session"
  #api tweet
  match "api/twitter_account_list" => "api/twitter_users#twitter_account_list"

  match "api/post_to_twitter" => "api/twitter_users#post_to_twitter"
  match "api/send_to_buff" => "api/twitter_users#send_to_buff"
  match 'twitter_users/delete_buffer/:id' => 'twitter_users#delete_buffer', :as => :delete_buffer, :via => :get
  match 'twitter_users/edit_buffer/:id' => 'twitter_users#edit_buffer', :as => :edit_buffer, :via => :get
  match "twitter_users/:id/update_buffer" => "twitter_users#update_buffer", :as => :update_buffer
  match "/settings/account/new" => "twitter_users#add_an_account", :as => :add_an_account
  match "invite_team_member" => 'TwitterUsers#invite_team_member', :via => :post, :as => :invite_team_member

  post "/save_settings" => "twitter_users#save_settings", :as => :save_settings

  resources :timezones

  resources :tweet_histories

  resources :tweet_intervals

  resources :timeframes
  
  resources :suggestions
  
  match "contact" => "contact#index", :as=> "contact"



  get "/goodies" => "goodies#index", :as => :goodies
  get "suggestions/tweet_suggestion/:twitter_name" => "suggestions#tweet_suggestion"
  
  match "setting_suggestion" => "Suggestions#setting_suggestion", :as => :setting_suggestion, :via => :get
  match "get_category/:id" => "Suggestions#get_category", :as => :get_category, :via => :post
  
  get "/update_setting_time" => "TwitterUsers#update_setting_time"

  resources :subcriptions
  resources :payment_notifications

  match "paypall_callback" => "dashboard#paypall_callback", :as => :paypall_callback

  resources :plans
  get "/plans/:id/signup" => "plans#get_plan_clicked_when_signup", :as => :get_plan_clicked_when_signup_plan
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  devise_for :users, :controllers => {:registrations => "devise/registration", :sessions => "devise/session", :passwords => "devise/password"}
 
  root :to => 'Home#index'  

  get "/settings/account" => "dashboard#account", :as => :account_settings
  put "/settings/account/update" => "dashboard#update", :as => :account_password_update
  
  match "/twitter/account/:twitter_name" => "twitterUsers#index", :as => :twitter_user
  match "/twitter/" => "twitterUsers#index", :as => :twitter_user2
  scope "dashboard" do
    get "/facebook/:twitter_name" => "TwitterUsers#index", :as => :facebook_user
    get "/twitter/:twitter_name" => "TwitterUsers#index", :as => :twitter_user
    
    controller :dashboard do
      get   "" => :show, :as => :dashboard
      get   "settings/twitter" => :twitter, :as => :twitter_settings
    end
  end
  
  get "/settings/twitter/:twitter_name" => "TwitterUsers#settings", :as => :twitter_settings
  get "/settings/facebook/:twitter_name" => "TwitterUsers#settings", :as => :facebook_settings
  
  scope "facebook" do
    controller :facebook_sessions do
      get   "authorize" => :new, :as => :facebook_authorize_account
      get   "callback" => :oauth_callback, :as => :facebook_callback
    end
    #    get "/settings" => "TwitterUsers#settings", :as => :facebook_settings
  end
   
  match "twitter/bitly_apis/delete/:id" => "bitly_apis#delete_bitly", :as => :delete_bitly, :via => :get
  
  scope "twitter" do
    #    match "add_account" => "dashboard#add_account", :as => :add_account
    get "/new" => "dashboard#add_account", :as => :add_account
    
    resources :bitly_apis do
      collection do
        post "save_detail" => :create_or_update
      end
    end
    
    controller :twitter_sessions do
      get   "authorize" => :new, :as => :twitter_authorize_account
      get   "callback" => :oauth_callback, :as => :twitter_callback
    end
    
    get "/" => "TwitterUsers#index", :as => :twitter_users
    
    get "/queue/:twitter_name" => "TwitterUsers#queue", :as => :twitter_user_queue
    get "/performance/:twitter_name" => "TwitterUsers#performance", :as => :twitter_user_performance
    
    get "/tweet_to_twitter" => "TwitterUsers#tweet_to_twitter", :as => :tweet_to_twitter
    get "/tweet_from_buffer/:id" => "TwitterUsers#tweet_from_buffer", :as => :tweet_from_buffer
    
    get "/twitter_account_list" => "TwitterUsers#twitter_account_list"
    
    #    get "/settings" => "TwitterUsers#settings", :as => :twitter_settings
    
    get "/settings/other_time_interval" => "TwitterUsers#other_time_interval", :as => :other_ti
    get "/settings/default_interval" => "TwitterUsers#default_interval", :as => :default_ti
    post "/settings/update_timezone" => "TwitterUsers#update_timezone", :as => :update_timezone
    post "/settings/update_notify" => "TwitterUsers#update_notify", :as => :update_notify

    scope ":twitter_name" do
      controller :buffer_preferences do
        get     "buffers"     => :index,    :as => :twitter_user_buffer_preferences
        post    "buffers"     => :create,   :as => :twitter_user_buffer_preferences
        get     "buffers/new" => :new,      :as => :new_twitter_user_buffer_preference
      end
      
      controller :suggestions do
        post    "suggestions"     => :create,   :as => :twitter_user_suggestions
      end

      scope ":buffer_name" do
        resources :tweets do
          collection do
            post :sort
          end
        end

        controller :buffer_preferences do
          get     "edit"  => :edit,             :as => :edit_twitter_user_buffer_preference
          get     "/"     => :show,             :as => :twitter_user_buffer_preference
          put     "/"     => :update,           :as => :twitter_user_buffer_preference
          delete  "/"     => :destroy,          :as => :twitter_user_buffer_preference
          get     "time"  => :new_tweet_time,   :as => :new_twitter_user_buffer_preference_tweet_time
        end

        post    "time" => "TimeDefinitions#create_time",  :as => :twitter_user_buffer_preference_tweet_time
        delete  "time" => "TimeDefinitions#destroy_time", :as => :twitter_user_buffer_preference_tweet_time
      end
    end
  end

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :subcriptions
  has_and_belongs_to_many :timeframes
end

app/controllers/plans_controller.rb
class PlansController < InheritedResources::Base
  before_filter :myplan, :only => [:index,:show]

  def myplan
    if user_signed_in?
      user = User.find(current_user.id)
      @myplan = user.subcriptions.last.plan.id rescue 0
    else
      @myplan = 0
    end
  end

  def get_plan_clicked_when_signup
    session[:plan_id] = params[:id]
    
    if user_signed_in?
      @cart = current_cart
      redirect_to @cart.paypal_url(twitter_users_url, payment_notifications_url)
    else
      redirect_to new_user_registration_path
    end
  end
  
end

app/helpers/plans_helper.rb
module PlansHelper
  def format_price_monthly(price)
    number_to_currency(price)
  end
  
  def format_price_years(price)
    price_year = price * 12
    diskon = (price_year * 15).to_f / 100.to_f
    sum = (price_year - diskon ).to_f / 12.to_f
    
    number_to_currency(sum.round(2))
  end  
end

app/views/plans/_form.html.haml
= simple_form_for(@plan) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :price
    = f.input :num_of_tweet_per_day
    = f.input :num_of_tweet_in_buffer
    = f.input :num_of_tweet_account
    = f.input :num_of_team_member_per_account
    = f.input :free_browser_ext

  .actions
    = f.button :submit

app/views/plans/_paypal_form.html.haml
%form{:id => "paypal" :action => "https://www.paypal.com/cgi-bin/webscr", :method => "post"}
  %input{:type => "submit", :value => "Signup now"}
  %input{:type => "hidden", :name => "item_name", :value => "buffer #{plan} subcription"}
  %input{:type => "hidden", :name => "a3", :value => price}
  %input{:type => "hidden", :name => "business", :value => "#{PAYPAL_USER}"}
  %input{:type => "hidden", :name => "cmd", :value => "_xclick-subscriptions"}
  %input{:type => "hidden", :name => "currency_code", :value => "USD"}
  %input{:type => "hidden", :name => "p3", :value => "1"}
  %input{:type => "hidden", :name => "t3", :value => "M"}
  %input{:type => "hidden", :name => "src", :value => "1"}
  %input{:type => "hidden", :name => "modify", :value => "1"}
  %input{:type => "hidden", :name => "custom", :value => current_user.email}
  %input{:type => "hidden", :name => "return", :value => "#{SERVER_URL}"
  
  
  

app/views/plans/edit.html.haml
%h1 Editing plan

= render 'form'

= link_to 'Show', @plan
\|
= link_to 'Back', plans_path

app/views/plans/index.html.haml
#middle.plansMiddle
  #configContainer
    #plansTabsContainer
      #plansTab1.plansTab_image_green
        %a.rockwellRegular{:href => "#"} Monthly
      #plansTab2.plansTab_image_blue
        %a.rockwellRegular{:href => "#"} 1 Year 15% OFF
    .separator/
  #plansContainer
    - classvar = ""
    - @plans.each do |plan|    
      .planContainer
        .plansContainer_left
        .plansContainer_body
          .planTitle 
            = plan.name
          .planPrice{:class=>"#{classvar}"}
            - case(plan.name)           
              -when "Pro"
                #{number_to_currency(plan.price)}/mo
              -when "Premium"
                #{number_to_currency(plan.price)}/mo
          .planPriceAnual{:class=>"hidden #{classvar}"}
            - case(plan.name)           
              -when "Pro"
                #{format_price_years(plan.price)}/mo
              -when "Premium"
                #{format_price_years(plan.price)}/mo      
          - case(plan.name)
            -when "Free"
              .planDescription Find out what it feels like to consitently tweet with buffer
            -when "Pro"
              .planDescription Tweet like a champ with custom metrics and larger buffer
            -when "Premium"
              .planDescription Enjoy the full power of professional GuyKawasaki-like tweeting
        .plansContainer_right
        %div{:style => "clear: both"}       
        .plansContainerBottomBody
          .planFeatures
            %p A continual stream of content for your followers
            %p 6 tweets per day
            %p 20 tweets in your Buffer
            %p 1 Twitter account
            %p Free browser extensions
            %p Use your Bit.ly details
            %p Daily Tweeting patterns
            %p Direct line to founder
        .plansContainerBottomBottom       
        %input.plansSignUpButton{:type => "button"}
      - if (classvar.empty?)
        -   classvar = 'priceColorOne'
      - else
        -   classvar = 'priceColorTwo'
  .planVideo
    #planVideoTitle
      See how it works in this short video
    #planVideoContainer
    %input.plansSignUpButtonBlue{:type => "button"}
      .readyMsg Ready to try Buffer? get started with it now for free
  .planReasons
    #planReasonsTitle
      Four reasons to try buffer now
    .planReason
      .planReasonBirdDiv
        .planReasonBirdDivWrapper
      .planReasonTitle
        Get more followers
      .planReasonDesc
        .planReasonDescWrapper
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare turpis vitae dolor luctus dapibus.
          %br/
          Sed congue elementum odio at tristique. Quisque sit amet sem tellus, aliquam bibendum dui.
          %br/
          Donec sagittis mi vitae turpis vestibulum nec vehicula tellus semper.
          %br/
          Vivamus consectetur dolor nec arcu sollicitudin sed lobortis erat accumsan. Morbi tempor malesuada leo at mattis. Sed libero diam, euismod ut iaculis ac, porttitor vel justo.
    .planReason
      .planReasonBirdDiv
        .planReasonBirdDivWrapper
      .planReasonTitle
        Get more followers
      .planReasonDesc
        .planReasonDescWrapper
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare turpis vitae dolor luctus dapibus.
          %br/
          Sed congue elementum odio at tristique. Quisque sit amet sem tellus, aliquam bibendum dui.
          %br/
          Donec sagittis mi vitae turpis vestibulum nec vehicula tellus semper.
          %br/
          Vivamus consectetur dolor nec arcu sollicitudin sed lobortis erat accumsan. Morbi tempor malesuada leo at mattis. Sed libero diam, euismod ut iaculis ac, porttitor vel justo.
    .planReason
      .planReasonBirdDiv
        .planReasonBirdDivWrapper
      .planReasonTitle
        Get more followers
      .planReasonDesc
        .planReasonDescWrapper
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare turpis vitae dolor luctus dapibus.
          %br/
          Sed congue elementum odio at tristique. Quisque sit amet sem tellus, aliquam bibendum dui.
          %br/
          Donec sagittis mi vitae turpis vestibulum nec vehicula tellus semper.
          %br/
          Vivamus consectetur dolor nec arcu sollicitudin sed lobortis erat accumsan. Morbi tempor malesuada leo at mattis. Sed libero diam, euismod ut iaculis ac, porttitor vel justo.
#sponsors.mainSponsors

app/views/plans/new.html.haml
%h1 New plan

= render 'form'

= link_to 'Back', plans_path

app/views/plans/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @plan.name
%p
  %b Price:
  = @plan.price
%p
  %b Num of tweet per day:
  = @plan.num_of_tweet_per_day
%p
  %b Num of tweet in buffer:
  = @plan.num_of_tweet_in_buffer
%p
  %b Num of tweet account:
  = @plan.num_of_tweet_account
%p
  %b Free browser ext:
  = @plan.free_browser_ext

= link_to 'Edit', edit_plan_path(@plan)
\|
= link_to 'Back', plans_path